### ISSUE TITLE
Action fails with io/console error

### ISSUE THREAD

**Issue by barnumbirr** [barnumbirr/action-forge-publish#2]
v1.1.0 currently fails with the following error

```bash
2020-05-04T12:53:50.9114073Z ##[group]Run barnumbirr/action-forge-publish@v2.1.0
2020-05-04T12:53:50.9114192Z with:
2020-05-04T12:53:50.9114369Z   REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
2020-05-04T12:53:50.9114515Z env:
2020-05-04T12:53:50.9114623Z   RELEASE_VERSION: v0.5.3
2020-05-04T12:53:50.9114853Z   FORGE_API_KEY: ***
2020-05-04T12:53:50.9114963Z ##[endgroup]
2020-05-04T12:53:50.9148152Z ##[command]/usr/bin/docker run --name c27d31298444e921fa48659c5178ad3e7ecba5_cfe058 --label c27d31 --workdir /github/workspace --rm -e RELEASE_VERSION -e FORGE_API_KEY -e INPUT_FORGE_API_KEY -e INPUT_REPOSITORY_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/puppet-zipkin/puppet-zipkin":"/github/workspace" c27d31:298444e921fa48659c5178ad3e7ecba5
2020-05-04T12:53:51.2897483Z REPOSITORY_URL environment variable is not set, using Puppet Forge.
2020-05-04T12:53:51.7822619Z /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- io/console (LoadError)
2020-05-04T12:53:51.7823153Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7823547Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty/reader/mode.rb:3:in `<top (required)>'
2020-05-04T12:53:51.7823953Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty/reader/console.rb:6:in `require_relative'
2020-05-04T12:53:51.7824384Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty/reader/console.rb:6:in `<top (required)>'
2020-05-04T12:53:51.7824770Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty/reader.rb:10:in `require_relative'
2020-05-04T12:53:51.7825166Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty/reader.rb:10:in `<top (required)>'
2020-05-04T12:53:51.7825553Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty-reader.rb:1:in `require_relative'
2020-05-04T12:53:51.7825939Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-reader-0.7.0/lib/tty-reader.rb:1:in `<top (required)>'
2020-05-04T12:53:51.7826291Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7833101Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7833637Z 	from /usr/lib/ruby/gems/2.6.0/gems/tty-prompt-0.20.0/lib/tty/prompt.rb:6:in `<top (required)>'
2020-05-04T12:53:51.7833975Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7834322Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7834678Z 	from /usr/lib/ruby/gems/2.6.0/gems/pdk-1.17.0/lib/pdk/cli/util/interview.rb:1:in `<top (required)>'
2020-05-04T12:53:51.7835254Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7835561Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7835901Z 	from /usr/lib/ruby/gems/2.6.0/gems/pdk-1.17.0/lib/pdk/cli/release.rb:4:in `<top (required)>'
2020-05-04T12:53:51.7836223Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7836539Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7836866Z 	from /usr/lib/ruby/gems/2.6.0/gems/pdk-1.17.0/lib/pdk/cli.rb:166:in `<module:CLI>'
2020-05-04T12:53:51.7837204Z 	from /usr/lib/ruby/gems/2.6.0/gems/pdk-1.17.0/lib/pdk/cli.rb:18:in `<top (required)>'
2020-05-04T12:53:51.7837637Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7837971Z 	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2020-05-04T12:53:51.7838300Z 	from /usr/lib/ruby/gems/2.6.0/gems/pdk-1.17.0/exe/pdk:3:in `<top (required)>'
2020-05-04T12:53:51.7838573Z 	from /usr/bin/pdk:23:in `load'
2020-05-04T12:53:51.7838859Z 	from /usr/bin/pdk:23:in `<main>'
2020-05-04T12:53:51.9318426Z Cleaning up orphan processes
```

**Comment by barnumbirr** [comment]
Fixed in [v2.2.0](https://github.com/barnumbirr/action-forge-publish/releases/tag/v2.2.0).
